# Writes the build stamp source file. Run as a script on every build (see vita/vita.cmake), so the stamp the
# log prints at boot always matches the binary. Decoding a crash dump needs the exact binary that made it.
#
# Inputs: OUT (file to write), SOURCE_DIR (repository root, for the git commit).

string(TIMESTAMP stamp_time "%Y-%m-%d %H:%M:%S")

execute_process(
    COMMAND git -C "${SOURCE_DIR}" rev-parse --short HEAD
    OUTPUT_VARIABLE stamp_commit
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if (NOT stamp_commit)
    set(stamp_commit "unknown")
endif()

execute_process(
    COMMAND git -C "${SOURCE_DIR}" status --porcelain --untracked-files=no --ignore-submodules=all
    OUTPUT_VARIABLE stamp_changes
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if (stamp_changes)
    set(stamp_commit "${stamp_commit} with uncommitted changes")
endif()

file(WRITE "${OUT}" "// Generated by vita/build_stamp.cmake on every build. Do not edit.\nconst char hm64_build_stamp[] = \"${stamp_time}, commit ${stamp_commit}\";\n")
